metadata:
  name: ${project.artifactId}
data:
  application.properties: |
    # spring application proeprties file
    spring.main.sources=com.lakshmi
    server.compression.mime-types = application/json,application/xml,text/xml,text/plain
    spring.main.web-environment = true
    
